services:
  db:
    image: timescale/timescaledb:latest-pg15
    container_name: diploma_postgres
    restart: always
    environment:
      POSTGRES_DB: telemetry
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - telemetry_network

  backend:
    build: ./backend
    container_name: diploma_backend
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - DATABASE_URL=postgresql://admin:admin_password@db:5432/telemetry
    depends_on:
      - db
    networks:
      - telemetry_network

  simulator:
    build: ./backend
    container_name: diploma_simulator
    restart: always
    volumes:
      - ./simulator:/app/simulator
    environment:
      - API_URL=http://backend:8000/ingest
      - CONFIG_URL=http://backend:8000/api/config
    command: python /app/simulator/simulator.py
    depends_on:
      - backend
    networks:
      - telemetry_network

  grafana:
    image: grafana/grafana:latest
    container_name: diploma_grafana
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - db
    networks:
      - telemetry_network

volumes:
  postgres_data:
  grafana_data:

networks:
  telemetry_network:
    name: telemetry_diploma_default